In [6]:
import pandas as pd
from skimage import color


ISCC_COLOR_PATH = "/home/erwin/Documents/AutoNeura/resources/files/iscc-nbs-colour-system.xlsx"

In [3]:
color_system = pd.read_excel(
    ISCC_COLOR_PATH
).dropna(subset=['r', 'g', 'b']).reset_index(drop=True)
color_system

color category      r      g      b
0       vivid_pink     pink  253.0  121.0  146.0
1      strong_pink     pink  244.0  143.0  160.0
2        deep_pink     pink  230.0  105.0  128.0
3       light_pink     pink  248.0  195.0  206.0
4    moderate_pink     pink  226.0  163.0  174.0
..             ...      ...    ...    ...    ...
255          white    white  231.0  225.0  233.0
256     light_gray     gray  189.0  183.0  191.0
257    medium_gray     gray  138.0  132.0  137.0
258      dark_gray     gray   88.0   84.0   88.0
259          black    black   43.0   41.0   43.0

[260 rows x 5 columns]

In [4]:
iscc_color = color_system[["color"]].values
iscc_category = color_system[["category"]].values
iscc_color, iscc_category

(array([['vivid_pink'],
        ['strong_pink'],
        ['deep_pink'],
        ['light_pink'],
        ['moderate_pink'],
        ['dark_pink'],
        ['pale_pink'],
        ['grayish_pink'],
        ['pinkish_white'],
        ['pinkish_gray'],
        ['vivid_red'],
        ['strong_red'],
        ['deep_red'],
        ['very_deep_red'],
        ['moderate_red'],
        ['dark_red'],
        ['very_dark_red'],
        ['light_grayish_red'],
        ['grayish_red'],
        ['dark_grayish_red'],
        ['blackish_red'],
        ['reddish_gray'],
        ['dark_reddish_gray'],
        ['reddish_black'],
        ['vivid_yellowish_pink'],
        ['strong_yellowish_pink'],
        ['deep_yellowish_pink'],
        ['light_yellowish_pink'],
        ['moderate_yellowish_pink'],
        ['dark_yellowish_pink'],
        ['pale_yellowish_pink'],
        ['grayish_yellowish_pink'],
        ['brownish_pink'],
        ['vivid_reddish_orange'],
        ['strong_reddish_orange'],
        ['deep

In [13]:
import colorsys
import numpy as np

def rgb_to_lab(R, G, B):
    # 1. Normalize and linearize RGB
    def to_linear(c):
        c = c / 255
        return ((c + 0.055) / 1.055) ** 2.4 if c > 0.04045 else c / 12.92

    r, g, b = map(to_linear, (R, G, B))

    # 2. Convert to XYZ
    X = r * 0.4124564 + g * 0.3575761 + b * 0.1804375
    Y = r * 0.2126729 + g * 0.7151522 + b * 0.0721750
    Z = r * 0.0193339 + g * 0.1191920 + b * 0.9503041

    # Normalize for D65
    X /= 0.95047
    Y /= 1.00000
    Z /= 1.08883

    # 3. Convert to Lab
    def f(t):
        return t ** (1/3) if t > 0.008856 else (7.787 * t) + (16 / 116)

    fx, fy, fz = f(X), f(Y), f(Z)
    L = (116 * fy) - 16
    a = 500 * (fx - fy)
    b = 200 * (fy - fz)

    return L, a, b


In [18]:
color_system[['r', 'g', 'b']].to_numpy()  / 255

array([[0.99215686, 0.4745098 , 0.57254902],
       [0.95686275, 0.56078431, 0.62745098],
       [0.90196078, 0.41176471, 0.50196078],
       [0.97254902, 0.76470588, 0.80784314],
       [0.88627451, 0.63921569, 0.68235294],
       [0.77254902, 0.50196078, 0.54117647],
       [0.9372549 , 0.81960784, 0.8627451 ],
       [0.79607843, 0.67843137, 0.71764706],
       [0.9372549 , 0.86666667, 0.89803922],
       [0.78039216, 0.71372549, 0.74117647],
       [0.83529412, 0.10980392, 0.23529412],
       [0.74901961, 0.20392157, 0.29411765],
       [0.52941176, 0.07058824, 0.17647059],
       [0.36078431, 0.02352941, 0.14509804],
       [0.69411765, 0.28627451, 0.33333333],
       [0.45490196, 0.14117647, 0.20392157],
       [0.28235294, 0.06666667, 0.15294118],
       [0.70588235, 0.53333333, 0.55294118],
       [0.59607843, 0.36470588, 0.38431373],
       [0.3254902 , 0.21960784, 0.24313725],
       [0.2       , 0.12941176, 0.15294118],
       [0.57254902, 0.50588235, 0.5254902 ],
       [0.

In [21]:
iscc_rgb = color_system[['r', 'g', 'b']].to_numpy() 
print(iscc_rgb[0])

[253. 121. 146.]


In [22]:
rgb_to_lab(iscc_rgb[0][0], iscc_rgb[0][1], iscc_rgb[0][2])

(67.00473448582215, 52.56258720372936, 10.844752844101247)

In [24]:
iscc_rgb = color_system[['r', 'g', 'b']].to_numpy() / 255
iscc_lab = color.rgb2lab(iscc_rgb)
iscc_lab[0]

array([67.00457593, 52.56151016, 10.84754151])